Stocktronic/Stocktronic/Controllers/ProductosController.cs
using Stocktronic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stocktronic.Controllers
{
    public class ProductosController : Controller
    {
        // GET: Producto
        public ActionResult Index()
        {
            try
            {
                ProductosModel productos = new ProductosModel();
                var listaProductos = productos.ListarProductos();
                return View(listaProductos);
            }
            catch (Exception)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        public ActionResult FormAgregarProducto()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        public ActionResult FormActualizarProducto(int idProducto)
        {
            try
            {
                ProductosModel producto = new ProductosModel();
                var productoSeleccionado = producto.ListarProducto(idProducto);
                return View(productoSeleccionado);
            }
            catch (Exception)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        [ChildActionOnly]
        public ActionResult ListarProveedores()
        {
            ProveedoresModel proveedor = new ProveedoresModel();
            var proveedores = proveedor.ListarProveedores();
            return PartialView("~/Views/Shared/_ListaProveedores.cshtml", proveedores);
        }


        [ChildActionOnly]
        public ActionResult ListarCategoria()
        {
            CategoriasModel categoria = new CategoriasModel();
            var categorias = categoria.ListarCategorias();
            return PartialView("~/Views/Shared/_ListaCategorias.cshtml", categorias);
        }

        [HttpGet]
        public ActionResult InsertarProducto(string nombre, string descripcion, string imagen, decimal precio, int cantidad, int idProveedor, int idCategoria)
        {
            ProductosModel producto = new ProductosModel();
            var exitoso = producto.InsertarProducto(nombre, descripcion, imagen, precio, cantidad, idProveedor, idCategoria);

            if (exitoso)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.DenyGet);
            }
        }

        [HttpGet]
        public ActionResult ActualizarProducto(int idProducto, string nombre, string descripcion, string imagen, decimal precio, int cantidad, int idProveedor, int idCategoria)
        {
            ProductosModel producto = new ProductosModel();
            var exitoso = producto.ActualizarProducto(idProducto, nombre, descripcion, imagen, precio, cantidad, idProveedor, idCategoria);

            if (exitoso)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.DenyGet);
            }
        }

        [HttpGet]
        public ActionResult EliminarProducto(int idProducto)
        {
            ProductosModel producto = new ProductosModel();
            var exitoso = producto.EliminarProducto(idProducto);

            if (exitoso)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.DenyGet);
            }
        }

    }
}

Stocktronic/Stocktronic/Views/Productos/FormActualizarProducto.cshtml
@model Stocktronic.Models.PF_PRODUCTO

@{
    ViewBag.Title = "FormActualizarProducto";
}

<head>
    <link href="~/Styles/checkout.css" rel="stylesheet" />
    <link href="~/Styles/formsButtons.css" rel="stylesheet" />
</head>

<body>

    <main class="page payment-page header-top">
        <section class="payment-form dark">
            <div class="container">
                <div class="block-heading">
                    <h2>Actualizar Producto</h2>
                </div>

                <!-- Begin Form -->
                <form action="" method="post">
                    <div class="card-details">
                        <h3 class="title text-uppercase">Actualizar Producto</h3>
                        <div class="row">
                            <div class="form-group col-sm-4">
                                <label id="idVal">ID Producto</label>
                                <input id="idProducto" name="id" type="number" class="form-control" placeholder="Identificador" value="@Model.ID_PRODUCTO" disabled>
                            </div>
                            <div class="form-group col-sm-8">
                                <label id="nomVal">Nombre Producto</label>
                                <input id="nombre" name="nombre" type="text" class="form-control" placeholder="Nombre" value="@Model.PRO_NOMBRE" required>
                            </div>
                            <div class="form-group col-sm-12">
                                <label id="descVal">Descripción Producto</label>
                                <input id="desc" name="desc" type="text" class="form-control" placeholder="Descripcion" value="@Model.PRO_DESCRIPCION" required>
                            </div>
                            <div class="form-group col-sm-12">
                                <label id="urlVal">URL Imagen</label>
                                <input id="url" name="url" type="text" class="form-control" placeholder="URL" value="@Model.PRO_URL_IMAGEN" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="precioVal">Precio Producto</label>
                                <input id="precio" name="precio" type="number" class="form-control" placeholder="Precio" value="@Model.PRO_PRECIO" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="cantVal">Cantidad Producto</label>
                                <input id="cant" name="cantidad" type="number" class="form-control" placeholder="Cantidad" value="@Model.PRO_CANTIDAD" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="proveedorVal">Proveedor</label>
                                @Html.Action("ListarProveedores")
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="categoriaVal">Categoría</label>
                                @Html.Action("ListarCategoria")
                            </div>
                            <div class="container">

                                <div class="row">
                                    <div class="form-group col-sm-6">
                                        <a href="@Url.Action("Index", "Productos")"><button id="cancelar" type="button" class="btn btn-block ">Cancelar</button></a>
                                    </div>
                                    <div class="form-group col-sm-6">
                                        <button id="btnUpdate" type="button" onclick="ActualizarProducto()" class="btn btn-block">Actualizar Producto</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </section>
    </main>

    <!-- Add sweetalert2 -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/Funciones/Producto.js"></script>

</body>

Stocktronic/Stocktronic/Views/Productos/FormAgregarProducto.cshtml
@{
    ViewBag.Title = "FormAgregarProducto";
}

<head>
    <link href="~/Styles/checkout.css" rel="stylesheet" />
    <link href="~/Styles/formsButtons.css" rel="stylesheet" />
</head>

<body>

    <main class="page payment-page header-top">
        <section class="payment-form dark">
            <div class="container">
                <div class="block-heading">
                    <h2>Agregar Producto</h2>
                </div>

                <!-- Begin Form -->
                <form action="" method="post">
                    <div class="card-details">
                        <h3 class="title text-uppercase">Agregar Producto</h3>
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label id="nomVal">Nombre Producto</label>
                                <input id="nombre" name="nombre" type="text" class="form-control" placeholder="Nombre" value="" required>
                            </div>
                            <div class="form-group col-sm-12">
                                <label id="descVal">Descripción Producto</label>
                                <input id="desc" name="desc" type="text" class="form-control" placeholder="Descripcion" value="" required>
                            </div>
                            <div class="form-group col-sm-12">
                                <label id="urlVal">URL Imagen</label>
                                <input id="url" name="url" type="text" class="form-control" placeholder="URL" value="" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="precioVal">Precio Producto</label>
                                <input id="precio" name="precio" type="number" class="form-control" placeholder="Precio" value="" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="cantVal">Cantidad Producto</label>
                                <input id="cant" name="cantidad" type="number" class="form-control" placeholder="Cantidad" value="" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="proveedorVal">Proveedor</label>
                                @Html.Action("ListarProveedores")
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="categoriaVal">Categoría</label>
                                @Html.Action("ListarCategoria")
                            </div>
                            <div class="container">

                                <div class="row">
                                    <div class="form-group col-sm-6">
                                        <a href="@Url.Action("Index", "Productos")"><button id="cancelar" type="button" class="btn btn-block ">Cancelar</button></a>
                                    </div>
                                    <div class="form-group col-sm-6">
                                        <button id="btnInsert" type="button" onclick="InsertarProducto()" class="btn btn-block">Insertar Producto</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </section>
    </main>

    <!-- Add sweetalert2 -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/Funciones/Producto.js"></script>

</body>

Stocktronic/Stocktronic/Views/Productos/Index.cshtml
@model IEnumerable<Stocktronic.Models.ProductosJoin>

@{ 
    ViewBag.Title = "TablaProductos"; 
}

<head>
    <link href="~/Styles/checkout.css" rel="stylesheet" />
    <!-- This link reference here is for the table pagination -->
    <link href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet'>
    <link href='https://cdn.datatables.net/buttons/1.7.1/css/buttons.dataTables.min.css' rel='stylesheet'>
</head>

<body>

    <div class="container header-top">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mt-5">
                <h2 class="heading-section">Inventario Stocktronic</h2>
                <a href="@Url.Action("FormAgregarProducto", "Productos")"><button class="btn btn-primary mt-3 mb-4">Agregar Producto</button></a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-wrap">
                    <table class="table" id="tblHistorial">
                        <thead class="thead-dark">
                            <tr class="text-center">
                                <th>#</th>
                                <th>Nombre</th>
                                <th>Imagen</th>
                                <th>Precio</th>
                                <th>Cantidad</th>
                                <th>Categoría</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var producto in Model)
                            {
                <tr class="text-center">
                    <th>@producto.ID_PRODUCTO</th>
                    <th>@producto.PRO_NOMBRE</th>
                    <td class="text-center"><img src="@producto.PRO_URL_IMAGEN" alt="imagen" width="90" height="90" /></td>
                    <td>@producto.PRECIO</td>
                    <td>@producto.CANTIDAD</td>
                    <td>@producto.CATEGORIA</td>
                    <td class="text-center">
                        <a href="@Url.Action("FormActualizarProducto", "Productos", new { idProducto = producto.ID_PRODUCTO })">
                            <button class="btn btn-success btn-md">Actualizar</button>
                        </a>
                        <button type="button" onclick="EliminarProducto(@producto.ID_PRODUCTO)" class="btn btn-danger btn-md btnDelete">Eliminar</button>
                    </td>
                </tr>
}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Add sweetalert2 -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/Funciones/Producto.js"></script>

    <!-- Scripts for the table pagination -->
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>

    <!-- Script for the buttons in general -->
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/dataTables.buttons.min.js"></script>

    <!-- This one is for the Excel button -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

    <!-- This two are for the PDF button -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>

    <!-- This two are for the Print button -->
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.print.min.js"></script>

</body>