Stocktronic/Stocktronic/Controllers/UsuariosController.cs
using Stocktronic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stocktronic.Controllers
{
    public class UsuariosController : Controller
    {

        public ActionResult Index()
        {
            try
            {
                UsuariosModel usuario = new UsuariosModel();
                var listaUsuarios = usuario.ListarUsuarios();
                return View(listaUsuarios);
            }
            catch (Exception)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        public ActionResult FormUsuarioInsertar()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        public ActionResult FormUsuarioActualizar(int idUsuario)
        {
            try
            {
                UsuariosModel usuario = new UsuariosModel();
                var usuarioSeleccionado = usuario.ListarUsuario(idUsuario);
                return View(usuarioSeleccionado);
            }
            catch (Exception)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        [ChildActionOnly]
        public ActionResult ListarRoles()
        {
            RolesModel rol = new RolesModel();
            var roles = rol.ListarRoles();
            return PartialView("~/Views/Shared/_ListaRoles.cshtml", roles);
        }

        [HttpGet]
        public ActionResult InsertarUsuario(string nombre, string apellido1, string apellido2, string correo, string password, int idRol)
        {
            UsuariosModel usuario = new UsuariosModel();
            var exitoso = usuario.InsertarUsuario(nombre, apellido1, apellido2, correo, password, idRol);

            if (exitoso)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.DenyGet);
            }
        }

        [HttpGet]
        public ActionResult ActualizarUsuario(int idUsuario, string nombre, string apellido1, string apellido2, string correo, string password, int idRol)
        {
            UsuariosModel usuario = new UsuariosModel();
            var exitoso = usuario.ActualizarUsuario(idUsuario, nombre, apellido1, apellido2, correo, password, idRol);

            if (exitoso)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.DenyGet);
            }
        }

        [HttpGet]
        public ActionResult EliminarUsuario(int idUsuario)
        {
            UsuariosModel usuario = new UsuariosModel();
            var exitoso = usuario.EliminarUsuario(idUsuario);

            if (exitoso)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.DenyGet);
            }
        }

    }
}

Stocktronic/Stocktronic/Views/Usuarios/FormUsuarioActualizar.cshtml
@model Stocktronic.Models.PF_USUARIO

@{
    ViewBag.Title = "FormActualizarUsuario";
}

<head>
    <link href="~/Styles/checkout.css" rel="stylesheet" />
    <link href="~/Styles/formsButtons.css" rel="stylesheet" />
</head>

<body>
    <main class="page payment-page header-top">
        <section class="payment-form dark">
            <div class="container">

                <div class="block-heading">
                    <h2>Actualizar Usuario</h2>
                </div>

                <!-- Begin Form -->
                <form action="" method="post">
                    <div class="card-details">
                        <h3 class="title text-uppercase">Actualizar Usuario</h3>
                        <div class="row">
                            <div class="form-group col-sm-6">
                                <label id="idVal">ID Usuario</label>
                                <input id="idUsuario" name="idUsuario" disabled type="text" class="form-control" placeholder="ID" value="@Model.ID_USUARIO" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="nomVal">Nombre</label>
                                <input id="nombre" name="nombre" maxlength="20" type="text" class="form-control" placeholder="Nombre" value="@Model.USR_NOMBRE" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="appVal">Primer Apellido</label>
                                <input id="apellido1" name="apellido1" maxlength="20" type="text" class="form-control" placeholder="Primer Apellido" value="@Model.USR_APELLIDO1" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="app2Val">Segundo Apellido</label>
                                <input id="apellido2" name="apellido2" maxlength="20" type="text" class="form-control" placeholder="Segundo Apellido" value="@Model.USR_APELLIDO2" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="emailVal">Correo Electrónico</label>
                                <input id="email" name="email" type="email" maxlength="80" class="form-control" placeholder="Correo Electrónico" value="@Model.USR_EMAIL" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="passVal">Contraseña</label>
                                <input id="password" name="password" type="password" maxlength="15" class="form-control" placeholder="Contraseña" value="@Model.USR_PASSWORD" required>
                            </div>

                            <div class="form-group col-sm-12">
                                <label id="tipoVal">Tipo de Usuario</label>
                                @Html.Action("ListarRoles")
                            </div>
                            <div class="container">

                                <div class="row">
                                    <div class="form-group col-sm-6">
                                        <a href="@Url.Action("Index", "Usuarios")"><button id="cancelar" type="button" class="btn btn-block ">Cancelar</button></a>
                                    </div>
                                    <div class="form-group col-sm-6">
                                        <button id="btnUpdate" type="button" onclick="ActualizarUsuario()" class="btn btn-block">Actualizar usuario</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </section>
    </main>

    <!-- Add sweetalert2 -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/Funciones/Usuario.js"></script>

</body>

Stocktronic/Stocktronic/Views/Usuarios/FormUsuarioInsertar.cshtml
@{
    ViewBag.Title = "FormAgregarUsuario";
}

<head>
    <link href="~/Styles/checkout.css" rel="stylesheet" />
    <link href="~/Styles/formsButtons.css" rel="stylesheet" />
</head>


<body>
    <main class="page payment-page header-top">
        <section class="payment-form dark">
            <div class="container">
                <div class="block-heading">
                    <h2>Agregar Usuario</h2>
                </div>

                <!-- Begin Form -->
                <form action="" method="post">
                    <div class="card-details">
                        <h3 class="title text-uppercase">Agregar Usuario</h3>
                        <div class="row">
                            <div class="form-group col-sm-6">
                                <label id="nomVal">Nombre</label>
                                <input id="nombre" name="nombre" maxlength="20" type="text" class="form-control" placeholder="Nombre" value="" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="appVal">Primer Apellido</label>
                                <input id="apellido1" name="apellido1" maxlength="20" type="text" class="form-control" placeholder="Primer Apellido" value="" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="app2Val">Segundo Apellido</label>
                                <input id="apellido2" name="apellido2" maxlength="20" type="text" class="form-control" placeholder="Segundo Apellido" value="" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="emailVal">Correo Electrónico</label>
                                <input id="email" name="email" type="mail" maxlength="80" class="form-control" placeholder="Correo Electrónico" value="" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="passVal">Contraseña</label>
                                <input id="password" name="password" type="password" maxlength="15" class="form-control" placeholder="Contraseña" value="" required>
                            </div>
                            <div class="form-group col-sm-6">
                                <label id="tipoVal">Tipo de usuario</label>
                                @Html.Action("ListarRoles")
                            </div>

                            <div class="container">
                                <div class="row">
                                    <div class="form-group col-sm-6">
                                        <a href="@Url.Action("Index", "Usuarios")"><button id="cancelar" type="button" class="btn btn-block ">Cancelar</button></a>
                                    </div>
                                    <div class="form-group col-sm-6">
                                        <button id="btnInsert" type="button" onclick="InsertarUsuario()" class="btn btn-block">Crear usuario</button>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </form>
            </div>
        </section>
    </main>

    <!-- Add sweetalert2 -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/Funciones/Usuario.js"></script>

</body>

Stocktronic/Stocktronic/Views/Usuarios/Index.cshtml
@model IEnumerable<Stocktronic.Models.UsuariosJoin>

@{
    ViewBag.Title = "TablaUsuarios";
}

<head>
    <link href="~/Styles/checkout.css" rel="stylesheet" />
    <!-- This link reference here is for the table pagination -->
    <link href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet'>
    <link href='https://cdn.datatables.net/buttons/1.7.1/css/buttons.dataTables.min.css' rel='stylesheet'>
</head>

<body>

    <div class="container header-top">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mt-5">
                <h2 class="heading-section">Lista de usuarios</h2>
                <a href="@Url.Action("FormUsuarioInsertar", "Usuarios")"><button class="btn btn-primary mt-3 mb-4">Agregar Usuario</button></a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-wrap">
                    <table class="table" id="tblHistorial">
                        <thead class="thead-dark">
                            <tr class="text-center">
                                <th>#</th>
                                <th>Nombre Completo</th>
                                <th>Correo electrónico</th>
                                <th>Tipo de Usuario</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var usuario in Model)
                            {
                                <tr class="text-center">
                                    <th>@usuario.ID_USUARIO</th>
                                    <td scope=row>@usuario.USR_NOMBRE @usuario.USR_APELLIDO1 @usuario.USR_APELLIDO2</td>
                                    <td>@usuario.USR_EMAIL</td>
                                    <td>@usuario.ROL_TIPO</td>
                                    <td class="text-center">
                                        <a href="@Url.Action("FormUsuarioActualizar", "Usuarios", new { idUsuario = usuario.ID_USUARIO })">
                                            <button class="btn btn-success btn-md">Actualizar</button>
                                        </a>
                                        <button type="button" onclick="EliminarUsuario(@usuario.ID_USUARIO)" class="btn btn-danger btn-md btnDelete">Eliminar</button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


    <!-- Add sweetalert2 -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/Funciones/Usuario.js"></script>

    <!-- Scripts for the table pagination -->
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>

    <!-- Script for the buttons in general -->
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/dataTables.buttons.min.js"></script>

    <!-- This one is for the Excel button -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

    <!-- This two are for the PDF button -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>

    <!-- This two are for the Print button -->
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.print.min.js"></script>

</body>